(define dx 0.1)

(define (smooth f)
    (lambda (x) 
        (let ((left-fx  (f (- x dx)))
                (fx (f x))
                (right-fx)  (f (+ x dx)) )
            (/ (+ left-fx fx right-fx) 3)     
        )
    )
)